(()=>{
const c=document.getElementById('gameCanvas'),x=c.getContext('2d'),T=30,W=32,H=20,world=[],mobs=[],companions=[];
let px=15,py=10,hp=10,maxHp=10,day=1,t=0,last=performance.now(),selected=0,xp=0,level=1,saveTimer=0;
const inv={wood:8,stone:4,iron:0,crystal:0,berry:4,meat:0,feather:0,scale:0,horn:0};
const gear={tool:'wooden pickaxe',weapon:'wooden sword',armor:'cloth'};const keys={};
const defs={
 phoenix:{n:'Phoenix',i:'🔥',req:{},perk:'Heals you sometimes.',ability:'Rebirth: restores health.',cool:0},
 unicorn:{n:'Unicorn',i:'🦄',req:{berry:8,crystal:2},perk:'Improves healing.',ability:'Radiant Heal: restores 3 HP.',cool:0},
 griffin:{n:'Griffin',i:'🦅',quest:{title:'Skybound Trial',need:{feather:3,crystal:5}},perk:'Protects you from danger.',ability:'Wind Strike: damages nearby mobs.',cool:0},
 dragon:{n:'Dragon',i:'🐉',quest:{title:'Heart of the Dragon',need:{crystal:12,iron:6}},perk:'Attacks hostile mobs.',ability:'Dragonfire: burns nearby mobs.',cool:0}
};
const quest={phoenix:'available',unicorn:'available',griffin:'available',dragon:'available'};
const icons={tree:'🌲',stone:'🪨',cactus:'🌵',ice:'🧊',crystal:'💎',ore:'⛏️',chest:'📦'};
function noise(a,b){return (Math.sin(a*12.9898+b*78.233)*43758.5453)%1}
function biome(a,b){if(a>23&&b<7)return'tundra';if(a<9&&b>12)return'desert';if(a>23&&b>12)return'crystal';let n=Math.abs(noise(Math.floor(a/6),Math.floor(b/5)));return n>.75?'swamp':n>.5?'forest':'meadow'}
function make(){world.length=0;mobs.length=0;companions.length=0;for(let y=0;y<H;y++){world[y]=[];for(let a=0;a<W;a++){let b=biome(a,y),r=Math.abs(noise(a*2,y*3)),z=b==='desert'?(r>.8?'cactus':'sand'):b==='tundra'?(r>.82?'ice':'snow'):b==='crystal'?(r>.72?'crystal':'purple'):b==='swamp'?(r>.8?'reed':'mud'):(r>.78?'tree':'grass');if(r>.91)z='stone';if(r>.965)z='ore';world[y][a]={b,z,h:['tree','stone','ore','cactus','ice','crystal'].includes(z)?3:1}}}
for(let i=0;i<12;i++)mob(['slime','goblin','wolf'][i%3]);
// A few guaranteed structures make exploration rewarding.
[[4,4],[27,15],[18,3]].forEach(([sx,sy])=>{if(world[sy]&&world[sy][sx])world[sy][sx].z='chest'});
px=15;py=10;hp=maxHp;day=1;t=0;xp=0;level=1;Object.keys(quest).forEach(k=>quest[k]='available');log('🌎 A new realm awaits! Explore, craft, battle, and discover hidden treasure.');save()}
function mob(type){mobs.push({type,x:2+Math.random()*(W-4),y:2+Math.random()*(H-4),hp:type==='goblin'?4:3,hit:0})}
function wild(type){companions.push({type,x:2+Math.random()*(W-4),y:2+Math.random()*(H-4),wild:true,follow:false,hp:5,maxHp:5})}
function tile(a,b){return world[Math.floor(b)]?.[Math.floor(a)]}
function blocked(a,b){let q=tile(a,b);return q&&['tree','stone','ore','chest'].includes(q.z)}
function log(s){let e=document.getElementById('gameLog');if(e)e.innerHTML='<div>'+s+'</div>'+e.innerHTML.slice(0,1800)}
function gainXP(n){xp+=n;let need=level*10;if(xp>=need){xp-=need;level++;maxHp++;hp=maxHp;log('⭐ Level '+level+'! Max health increased.')} }
function save(){try{localStorage.setItem('realmcraft-save',JSON.stringify({world,px,py,hp,maxHp,day,t,inv,gear,quest,companions,xp,level}))}catch(e){}}
function load(){try{let d=JSON.parse(localStorage.getItem('realmcraft-save'));if(!d)return false;world.splice(0,world.length,...d.world);px=d.px;py=d.py;hp=d.hp;maxHp=d.maxHp||10;day=d.day;t=d.t;Object.assign(inv,d.inv);Object.assign(gear,d.gear);Object.assign(quest,d.quest);companions.splice(0,companions.length,...(d.companions||[]));xp=d.xp||0;level=d.level||1;return true}catch(e){return false}}
function has(r){return Object.entries(r).every(([k,v])=>(inv[k]||0)>=v)}function spend(r){Object.entries(r).forEach(([k,v])=>inv[k]-=v)}
function tame(type){let d=defs[type];if(d.quest){if(quest[type]==='available'){quest[type]='active';log('📜 '+d.quest.title+' started! Gather '+Object.entries(d.quest.need).map(q=>q[1]+' '+q[0]).join(' and ')+'.')}else if(quest[type]==='active'&&has(d.quest.need)){spend(d.quest.need);quest[type]='tamed';companions.push({type,x:px+1,y:py,follow:true,wild:false,hp:8,maxHp:8});gainXP(15);log(d.i+' '+d.n+' has joined you!')}else log('Quest: '+d.quest.title+' — '+Object.entries(d.quest.need).map(q=>q[1]+' '+q[0]).join(' and '));save();return}if(quest[type]==='available'&&has(d.req)){spend(d.req);quest[type]='tamed';companions.push({type,x:px+1,y:py,follow:true,wild:false,hp:6,maxHp:6});gainXP(8);log(d.i+' '+d.n+' was tamed!')}else log(d.n+' requires '+Object.entries(d.req).map(q=>q[1]+' '+q[0]).join(' and '));save()}
function interact(){let a=Math.floor((mouse.x/c.width)*W),b=Math.floor((mouse.y/c.height)*H),q=tile(a,b);if(Math.hypot(a+.5-px,b+.5-py)>3)return;
if(q&&['tree','stone','cactus','ice','crystal','ore','chest'].includes(q.z)){if(q.z==='chest'){inv.iron+=2;inv.crystal++;gainXP(5);q.z='grass';log('📦 You found treasure: 2 iron and 1 crystal!');save();return}q.h--;if(q.h<=0){let g={tree:'wood',stone:'stone',ore:'iron',cactus:'berry',ice:'stone',crystal:'crystal'}[q.z];inv[g]++;if(q.z==='tree'&&Math.random()<.3)inv.feather++;if(q.z==='crystal'&&Math.random()<.15)inv.horn++;q.z='grass';q.h=1;gainXP(1);log('Collected '+g+'!');save()}return}
for(const m of mobs.slice()){if(Math.hypot(m.x-a-.5,m.y-b-.5)<1){let dmg=gear.weapon==='iron sword'?2:1;m.hp-=dmg;if(m.hp<=0){inv.meat++;if(m.type==='wolf'&&Math.random()<.3)inv.feather++;if(m.type==='goblin'&&Math.random()<.2)inv.iron++;gainXP(3);mobs.splice(mobs.indexOf(m),1);mob(m.type);log('⚔️ Defeated a '+m.type+'!')}}}
companions.filter(z=>z.wild).forEach(z=>{if(Math.hypot(z.x-a-.5,z.y-b-.5)<1.2)tame(z.type)})}
const mouse={x:0,y:0};c.onmousemove=e=>{let r=c.getBoundingClientRect();mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top};c.onmousedown=interact;
onkeydown=e=>{keys[e.key.toLowerCase()]=1;if(/^\d$/.test(e.key)&&e.key<='6')selected=+e.key-1;if(e.key.toLowerCase()==='r'&&inv.berry&&hp<maxHp){inv.berry--;hp=Math.min(maxHp,hp+2+(quest.unicorn==='tamed'?1:0));log('🫐 You ate a berry.')}if(e.key.toLowerCase()==='e')craft(0);if(e.key.toLowerCase()==='q')ability()};onkeyup=e=>keys[e.key.toLowerCase()]=0;
function craft(i){let r=[['Stone Pickaxe',{stone:5}],['Iron Sword',{iron:3,wood:2}],['Crystal Armor',{crystal:8,iron:4}],['Torch',{wood:1,stone:1}],['Axe',{wood:3,stone:2}],['Bow',{wood:4,feather:2}]][i];if(!r)return;if(has(r[1])){spend(r[1]);if(i===0)gear.tool='stone pickaxe';if(i===1)gear.weapon='iron sword';if(i===2)gear.armor='crystal armor';if(i===4)gear.tool='axe';if(i===5)gear.weapon='bow';gainXP(2);log('🛠️ Crafted '+r[0]+'!');save()}else log('Not enough resources.')}
function ability(){let active=companions.find(z=>z.follow);if(!active){log('You need a tamed companion to use Q.');return}let d=defs[active.type];if(d.cool>0){log('✨ '+d.n+' is resting.');return}if(active.type==='phoenix'){hp=Math.min(maxHp,hp+2);log('🔥 Phoenix restored 2 HP!')}else if(active.type==='unicorn'){hp=Math.min(maxHp,hp+3);log('🦄 Radiant Heal restored 3 HP!')}else{mobs.forEach(m=>{if(Math.hypot(m.x-px,m.y-py)<3)m.hp-=active.type==='dragon'?4:2});log(d.i+' '+d.ability)}d.cool=8;save()}
function ui(){let b=tile(px,py)?.b||'meadow';document.getElementById('biomeLabel').textContent=b[0].toUpperCase()+b.slice(1);document.getElementById('dayLabel').textContent=day;document.getElementById('healthLabel').textContent=hp+'/'+maxHp;document.getElementById('gameStats').innerHTML='🪵 '+inv.wood+' · 🪨 '+inv.stone+' · ⛓️ '+inv.iron+' · 💎 '+inv.crystal+' · 🫐 '+inv.berry+' · 🥩 '+inv.meat+' · 🪶 '+inv.feather+' · 🐉 '+inv.scale+' · 🦄 '+inv.horn+'<br>⭐ Level '+level+' · XP '+xp+'/'+(level*10)+'<br>🛡️ '+gear.armor+' · ⚔️ '+gear.weapon+' · ⛏️ '+gear.tool+'<br><span class="muted">Q: companion ability</span>';
document.getElementById('hotbar').innerHTML=[['wood','🪵'],['stone','🪨'],['iron','⛓️'],['crystal','💎'],['berry','🫐'],['meat','🥩']].map((s,i)=>`<div class="slot ${i===selected?'selected':''}">${i+1} ${s[1]} ${inv[s[0]]}</div>`).join('');
document.getElementById('craftingList').innerHTML=[['Stone Pickaxe','5 stone',0],['Iron Sword','3 iron + 2 wood',1],['Crystal Armor','8 crystal + 4 iron',2],['Torch','1 wood + 1 stone',3],['Axe','3 wood + 2 stone',4],['Bow','4 wood + 2 feathers',5]].map(r=>`<div class="companion"><b>${r[0]}</b><br><span class="muted">${r[1]}</span> <button onclick="craft(${r[2]})">Craft</button></div>`).join('');
document.getElementById('companionList').innerHTML=Object.entries(defs).map(([k,d])=>`<div class="companion"><b>${d.i} ${d.n}</b> — ${quest[k]==='tamed'?'Tamed ✓':quest[k]==='active'?'Quest active 📜':'Available'}<br><span class="muted">${d.perk} ${d.ability}</span> <button onclick="tame('${k}')">${d.quest?(quest[k]==='active'?'Turn in':'Quest'): 'Tame'}</button></div>`).join('')}
function block(a,b,q){const tw=c.width/W,th=c.height/H,px0=a*tw,py0=b*th;const floors={meadow:'#67a94f',forest:'#3f7d45',desert:'#d6b66a',tundra:'#c7d9df',swamp:'#526f52',crystal:'#514876'};x.fillStyle=floors[q.b]||'#67a94f';x.fillRect(px0,py0,tw+1,th+1);x.strokeStyle='rgba(0,0,0,.10)';x.strokeRect(px0+.5,py0+.5,tw-1,th-1);const z=q.z;if(z==='tree'){x.fillStyle='#6b4226';x.fillRect(px0+11,py0+13,8,17);x.fillStyle='#2f6b38';x.fillRect(px0+4,py0+5,22,15);x.fillStyle='#3d8345';x.fillRect(px0+8,py0+2,14,8)}else if(z==='stone'){x.fillStyle='#777';x.fillRect(px0+2,py0+2,26,26);x.fillStyle='#999';x.fillRect(px0+5,py0+5,7,5);x.fillStyle='#5d5d5d';x.fillRect(px0+17,py0+15,8,6)}else if(z==='ore'){x.fillStyle='#666';x.fillRect(px0+2,py0+2,26,26);x.fillStyle='#b87552';x.fillRect(px0+6,py0+8,6,6);x.fillRect(px0+18,py0+18,5,5)}else if(z==='cactus'){x.fillStyle='#2f7d43';x.fillRect(px0+11,py0+4,8,24);x.fillRect(px0+5,py0+12,7,6);x.fillRect(px0+18,py0+9,7,6)}else if(z==='ice'){x.fillStyle='#a9d8e5';x.fillRect(px0+2,py0+2,26,26);x.fillStyle='#e8fbff';x.fillRect(px0+7,py0+6,4,18);x.fillRect(px0+17,py0+9,4,14)}else if(z==='crystal'){x.fillStyle='#6d4fd1';x.fillRect(px0+2,py0+2,26,26);x.fillStyle='#d6b7ff';x.fillRect(px0+10,py0+5,7,20);x.fillRect(px0+6,py0+11,6,12);x.fillRect(px0+17,py0+13,6,11)}else if(z==='chest'){x.fillStyle='#8b542d';x.fillRect(px0+4,py0+9,22,16);x.fillStyle='#c58a42';x.fillRect(px0+5,py0+7,20,7);x.fillStyle='#f1cf55';x.fillRect(px0+13,py0+13,4,6)}else if(z==='grass'||z==='sand'||z==='snow'||z==='mud'||z==='reed'||z==='purple'){if(z==='reed'){x.fillStyle='#3d7040';x.fillRect(px0+6,py0+8,3,18);x.fillRect(px0+14,py0+5,3,21);x.fillRect(px0+22,py0+10,3,16)}}}
function actor(px0,py0,type){const tw=c.width/W,th=c.height/H,X=px0*tw,Y=py0*th;let body='#8b5cf6',skin='#f2c49b';if(type==='player'){x.fillStyle='#263238';x.fillRect(X+9,Y+3,12,7);x.fillStyle=skin;x.fillRect(X+9,Y+10,12,9);x.fillStyle='#4f8cff';x.fillRect(X+7,Y+19,7,9);x.fillRect(X+16,Y+19,7,9)}else if(type==='slime'){x.fillStyle='#37c85a';x.fillRect(X+5,Y+8,20,17);x.fillStyle='#163b1d';x.fillRect(X+10,Y+13,3,3);x.fillRect(X+18,Y+13,3,3)}else if(type==='goblin'){x.fillStyle='#5c9d45';x.fillRect(X+8,Y+6,14,10);x.fillStyle='#2e4426';x.fillRect(X+7,Y+16,16,10);x.fillStyle='#111';x.fillRect(X+11,Y+9,3,3);x.fillRect(X+17,Y+9,3,3)}else if(type==='wolf'){x.fillStyle='#777';x.fillRect(X+5,Y+11,20,12);x.fillRect(X+8,Y+7,5,6);x.fillRect(X+18,Y+7,5,6);x.fillStyle='#222';x.fillRect(X+10,Y+14,3,3);x.fillRect(X+18,Y+14,3,3)}else if(type==='phoenix'){x.fillStyle='#e34b2f';x.fillRect(X+7,Y+8,16,16);x.fillStyle='#ffb52e';x.fillRect(X+11,Y+4,8,22)}else if(type==='unicorn'){x.fillStyle='#eee';x.fillRect(X+7,Y+9,17,15);x.fillStyle='#f4a7d7';x.fillRect(X+17,Y+4,5,7);x.fillStyle='#ffd86b';x.fillRect(X+11,Y+3,3,7)}else if(type==='griffin'){x.fillStyle='#9b6b3e';x.fillRect(X+6,Y+8,19,16);x.fillStyle='#d9c08a';x.fillRect(X+2,Y+11,8,9);x.fillRect(X+22,Y+11,6,9)}else if(type==='dragon'){x.fillStyle='#4d9a50';x.fillRect(X+5,Y+7,21,18);x.fillStyle='#a7d66a';x.fillRect(X+9,Y+12,12,8);x.fillStyle='#efc34a';x.fillRect(X+21,Y+5,5,8)}}
function draw(){x.clearRect(0,0,c.width,c.height);for(let y=0;y<H;y++)for(let a=0;a<W;a++)block(a,y,world[y][a]);mobs.forEach(m=>actor(m.x,m.y,m.type));companions.forEach(z=>actor(z.x,z.y,z.type));actor(px,py,'player');let night=(Math.sin((t/30)*Math.PI*2)>0.45);if(night){x.fillStyle='rgba(20,20,55,.28)';x.fillRect(0,0,c.width,c.height)}ui()}

function update(dt){let vx=(keys.d?1:0)-(keys.a?1:0),vy=(keys.s?1:0)-(keys.w?1:0),l=Math.hypot(vx,vy)||1;if(vx||vy){let nx=Math.max(.5,Math.min(W-.5,px+vx/l*3*dt)),ny=Math.max(.5,Math.min(H-.5,py+vy/l*3*dt));if(!blocked(nx,py))px=nx;if(!blocked(px,ny))py=ny}
t+=dt;mobs.forEach(m=>{let dx=px-m.x,dy=py-m.y,d=Math.hypot(dx,dy);if(d<7&&d>1){m.x+=dx/d*.35*dt;m.y+=dy/d*.35*dt}if(d<1.1){m.hit+=dt;if(m.hit>1.5){let reduction=gear.armor==='crystal armor'?.5:gear.armor==='cloth'?.8:1;hp=Math.max(0,hp-Math.ceil(reduction));m.hit=0;if(hp<=0){hp=maxHp;px=15;py=10;log('💫 You were knocked out and returned home.')}}}});
if(t>30){t=0;day++;mob('goblin');if(day%2===0)wild(Math.random()<.5?'phoenix':'unicorn');if(day%3===0&&quest.griffin!=='tamed')wild('griffin');if(day%5===0&&quest.dragon!=='tamed')wild('dragon');log('🌙 Day '+day+' begins. Magical creatures are appearing!')}
companions.forEach(z=>{let d=defs[z.type];d.cool=Math.max(0,d.cool-dt);if(z.follow){let dx=px-z.x,dy=py-z.y,dist=Math.hypot(dx,dy);if(dist>1.5){z.x+=dx/dist*1.7*dt;z.y+=dy/dist*1.7*dt}}if(z.type==='phoenix'&&Math.random()<.001&&hp<maxHp)hp++;if(z.type==='dragon')mobs.forEach(m=>{if(Math.hypot(m.x-z.x,m.y-z.y)<2)m.hp-=dt})});saveTimer+=dt;if(saveTimer>5){save();saveTimer=0}}
document.getElementById('newWorldBtn').onclick=()=>{if(confirm('Start a new Realmcraft world? Your current save will be replaced.'))make()};if(!load())make();function loop(n){let dt=Math.min(.05,(n-last)/1000);last=n;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);window.craft=craft;window.tame=tame;window.ability=ability;
})();